apiVersion: v1
kind: Service
metadata:
  name: login-page-service
  namespace: sopra-hr
  labels:
    app: login-page
    app.kubernetes.io/name: login-page-service
    app.kubernetes.io/part-of: login-page-replicator
spec:
  selector:
    app: login-page
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

